const fs = require("fs");
const path = require("path");
const mysql = require("mysql2");
const cliProgress = require("cli-progress");
const { fetchChapters } = require("../quran-seed/chapters");
const { fetchVersesAndWords, TOTAL_PAGES } = require("../quran-seed/verses-words");
const {
  deriveRubs,
  deriveRubVerseMappings,
  derivePageMetadata,
} = require("../quran-seed/derive");
const {
  fetchMushafLayout,
  layoutFromSeededWords,
  LAYOUT_MUSHAF_IDS,
  DEFAULT_MUSHAF_ID,
} = require("../quran-seed/mushaf-layout");

// Full dataset, not a trim — see docs/plans/visual-e2e-testing.md Addendum 1:
// `generateStaticParams` hardcodes all 604 pages, so `next build` requires
// every page to have data regardless of which pages the tests screenshot.
const OUT_FILE = path.join(__dirname, "../../e2e/fixtures/quran-fixture.sql");
const CHUNK = 500;

/** One `INSERT ... VALUES` per CHUNK rows, to stay well under MySQL's packet size limit. */
function insertStatements(table, rows) {
  if (rows.length === 0) return "";
  const columns = Object.keys(rows[0]);
  let sql = "";
  for (let i = 0; i < rows.length; i += CHUNK) {
    const values = rows
      .slice(i, i + CHUNK)
      .map((row) => `(${columns.map((c) => mysql.escape(row[c])).join(", ")})`)
      .join(",\n  ");
    sql += `INSERT INTO \`${table}\` (${columns.map((c) => `\`${c}\``).join(", ")}) VALUES\n  ${values};\n\n`;
  }
  return sql;
}

async function main() {
  console.log(`Fetching chapters…`);
  const chapters = await fetchChapters();

  console.log(`Fetching verses + words (${TOTAL_PAGES} pages)…`);
  const bar = new cliProgress.SingleBar({}, cliProgress.Presets.shades_classic);
  bar.start(TOTAL_PAGES, 0);
  const { verses, words } = await fetchVersesAndWords((page) => bar.update(page));
  bar.stop();

  // Per-edition word placement. `getPageWords` composes every page from
  // `mushaf_word_layouts` and reads `mushaf_page_metadata` with findFirstOrThrow
  // (ADR 0033), so a fixture without these tables renders empty pages and fails
  // the build outright — they are not optional extras here.
  const mushafWordLayouts = [];
  const mushafPageMetadata = [];
  for (const mushafId of LAYOUT_MUSHAF_IDS) {
    let rows;
    let pageOf;
    if (mushafId === DEFAULT_MUSHAF_ID) {
      console.log(`Deriving mushaf=${mushafId} word placement from fetched words…`);
      rows = layoutFromSeededWords(mushafId, words);
      pageOf = (v) => v.page_number;
    } else {
      console.log(`Fetching mushaf=${mushafId} word placement (${TOTAL_PAGES} pages)…`);
      const layoutBar = new cliProgress.SingleBar({}, cliProgress.Presets.shades_classic);
      layoutBar.start(TOTAL_PAGES, 0);
      const fetched = await fetchMushafLayout(
        mushafId,
        new Set(words.map((w) => w.id)),
        (page) => layoutBar.update(page)
      );
      layoutBar.stop();
      rows = fetched.rows;
      pageOf = (v) => fetched.versePages.get(v.verse_key);
    }
    mushafWordLayouts.push(...rows);
    mushafPageMetadata.push(
      ...derivePageMetadata(verses, pageOf).map((row) => ({
        ...row,
        mushaf_id: mushafId,
      }))
    );
  }

  console.log(`Deriving rubs / rub_verse_mappings / page_metadata…`);
  const rubs = deriveRubs(verses);
  const rubVerseMappings = deriveRubVerseMappings(verses);
  const pageMetadata = derivePageMetadata(verses);

  const sql =
    "-- Generated by scripts/e2e-fixture/generate.js — do not hand-edit.\n" +
    "-- Regenerate with `npm run e2e:generate-fixture` (see docs/plans/visual-e2e-testing.md).\n\n" +
    insertStatements("chapters", chapters) +
    insertStatements("verses", verses) +
    insertStatements("words", words) +
    insertStatements("mushaf_word_layouts", mushafWordLayouts) +
    insertStatements("rubs", rubs) +
    insertStatements("rub_verse_mappings", rubVerseMappings) +
    insertStatements("page_metadata", pageMetadata) +
    insertStatements("mushaf_page_metadata", mushafPageMetadata);

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, sql);

  console.log(
    `\n✓ Wrote ${OUT_FILE}\n` +
      `  chapters=${chapters.length} verses=${verses.length} words=${words.length} ` +
      `mushaf_word_layouts=${mushafWordLayouts.length} rubs=${rubs.length} ` +
      `rub_verse_mappings=${rubVerseMappings.length} page_metadata=${pageMetadata.length} ` +
      `mushaf_page_metadata=${mushafPageMetadata.length}`
  );
}

main().catch((e) => {
  console.error("\nFixture generation failed:", e.message);
  process.exit(1);
});
