import fs from "fs/promises";
import path from "path";
import { SurahResult } from "@/app/types";

// Static content generated by `npm run generate:quran-chapters` (Static Generation
// Strategy decision — the 114 surahs never change without a full Quran reseed, so
// this is pre-computed rather than queried from the DB at request time).
const CHAPTERS_FILE = path.join(process.cwd(), "public/quran/chapters.json");

function isSurahResultArray(value: unknown): value is SurahResult[] {
    return (
        Array.isArray(value) &&
        value.length > 0 &&
        value.every(
            (v) =>
                typeof v.id === "number" &&
                typeof v.name_arabic === "string" &&
                typeof v.name_simple === "string" &&
                typeof v.verses_count === "number" &&
                typeof v.revelation_place === "string" &&
                typeof v.pages === "string"
        )
    );
}

let cachedSurahs: SurahResult[] | null = null;

export const getSurahs = async (): Promise<SurahResult[]> => {
    if (cachedSurahs) {
        return cachedSurahs;
    }

    let parsed: unknown;
    try {
        const raw = await fs.readFile(CHAPTERS_FILE, "utf-8");
        parsed = JSON.parse(raw);
    } catch (err) {
        throw new Error(
            `Failed to read ${CHAPTERS_FILE} — run \`npm run generate:quran-chapters\` to regenerate it.`,
            { cause: err }
        );
    }

    if (!isSurahResultArray(parsed)) {
        throw new Error(
            `${CHAPTERS_FILE} does not match the expected SurahResult[] shape — regenerate it with \`npm run generate:quran-chapters\`.`
        );
    }

    cachedSurahs = parsed;
    return cachedSurahs;
};
